CREATE TABLE users (
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);

CREATE TABLE products (
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    product_name VARCHAR(50) NOT NULL DEFAULT 'N/A',
    description VARCHAR(100) NOT NULL DEFAULT 'N/A',
    location INT(11) NOT NULL,
    quantity INT(11) NOT NULL DEFAULT 0,
    supplier INT(11) NOT NULL,
    created_by INT(11) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE locations (
    id INT(11) NOT NULL AUTO_INCREMENT,
    location_name VARCHAR(50) NOT NULL DEFAULT 'N/A',
    location_description VARCHAR(200) NOT NULL DEFAULT 'N/A',
    created_by INT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

ALTER TABLE locations
ADD CONSTRAINT fk_created_by
FOREIGN KEY (created_by) REFERENCES users(id)
ON DELETE CASCADE;


ALTER TABLE products 
ADD CONSTRAINT fk_location FOREIGN KEY (location) REFERENCES locations(id) 
ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE suppliers (
    id INT(11) NOT NULL AUTO_INCREMENT,
    supplier_name VARCHAR(50) NOT NULL DEFAULT 'N/A',
    supplier_cuit VARCHAR(14) NOT NULL DEFAULT '0',
    supplier_location VARCHAR(200) NOT NULL DEFAULT 'N/A',
    supplier_description VARCHAR(200) NOT NULL DEFAULT 'N/A',
    supplier_email VARCHAR(100) NOT NULL DEFAULT 'N/A',
    created_by INT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

ALTER TABLE suppliers
ADD CONSTRAINT fk_created_by
FOREIGN KEY (created_by) REFERENCES users(id)
ON DELETE CASCADE;

ALTER TABLE products 
ADD CONSTRAINT fk_supplier FOREIGN KEY (supplier) REFERENCES suppliers(id) 
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE products 
ADD CONSTRAINT fk_created_by FOREIGN KEY (created_by) REFERENCES users(id) 
ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE orders (
    id INT NOT NULL AUTO_INCREMENT,
    product INT NOT NULL,
    supplier INT NOT NULL,
    ordered_quantity INT NOT NULL DEFAULT 1,  
    PRIMARY KEY (id)
);

ALTER TABLE orders
ADD CONSTRAINT fk_product
FOREIGN KEY (product) REFERENCES products(id)
ON DELETE CASCADE;

ALTER TABLE orders
ADD CONSTRAINT fk_supplier
FOREIGN KEY (supplier) REFERENCES suppliers(id)
ON DELETE CASCADE;

ALTER TABLE orders
ADD CONSTRAINT fk_user
FOREIGN KEY (created_by) REFERENCES users(id)
ON DELETE CASCADE;

